# --- Build stage ---
FROM node:22-alpine AS builder
WORKDIR /app

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

COPY package.json .npmrc ./
# pnpm-lock.yaml is intentionally not copied — it is not tracked in git
# (the only committed lockfile is package-lock.json, generated by npm).
# `--no-frozen-lockfile` lets pnpm build the lockfile fresh on first build,
# and `--prefer-offline` makes subsequent CI builds reuse the in-image cache.
RUN npm install -g pnpm && pnpm install --no-frozen-lockfile --prefer-offline

COPY . .
RUN pnpm build

# --- Production stage ---
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup -S hermes && adduser -S hermes -G hermes

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/server-entry.js ./

EXPOSE 3000

USER hermes

CMD ["node", "server-entry.js"]

